#!/bin/bash

alias l='ls -lh --color=auto'
alias ll='ls -ahlF --color=auto'
alias ..="cd .."
alias vi=vim
alias vim="vim -p"
alias mvnci="mvn clean install -DskipTests=true"
alias pm="podman"

#alias ssh="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
alias scp="scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

# cd mapped as cd and ls
cd_and_ls() {
  cd $1;
  if [ -z $KUBE_ENV ]; then
    current_dir=`basename $(pwd)`
    tmux rename-window $current_dir
  fi
  ls;
}

goto() {
  upperCased=$(echo $1 | tr '[a-z]' '[A-Z]')
  definedVarName="GOTO_$upperCased"
  eval cd "\"\${$definedVarName?}\""
}
alias g=goto
alias cd="cd_and_ls"
