#!/bin/bash

[ -f ~/.common_exports ] && . ~/.common_exports
[ -f ~/.exports ] && . ~/.exports
[ -f ~/.common_aliases ] && . ~/.common_aliases
[ -f ~/.aliases ] && . ~/.aliases
[ -f /etc/bashrc ] && . /etc/bashrc

