#!/bin/bash

[ -f ~/.profile ] && . ~/.profile
[ -f ~/.common_exports ] && . ~/.common_exports
[ -f ~/.exports ] && . ~/.exports
[ -f ~/.aliases ] && . ~/.aliases
[ -f /etc/bashrc ] && . /etc/bashrc

