Globals:
  exitOnError: true
  confirmEveryPackage: true

includes:
  - common_system.yml
  - editors.yml
  - tmux.yml
  - k8s.yml
  - git.yml

FileAction:
  aliases:
    hidden: true
    source: ../home
    command: ln -s
    destination: $#HOME#$
  bashrc:
    hidden: true
    source: ../home
    command: ln -s
    destination: $#HOME#$
  exports:
    hidden: true
    source: ../home
    command: ln -s
    destination: $#HOME#$
