#!/bin/bash
installer=apt
    sudo $installer install cups
    sudo $installer install mc
    sudo $installer install vim
    #sudo $installer install thunderbird
    #sudo $installer install clementine
    sudo $installer install tmux
    sudo $installer install sysstat
    sudo $installer install samba
    sudo $installer install ngrep
    sudo $installer install ssh
    sudo $installer install tree
    sudo $installer install openvpn
    #sudo $installer install guake
    sudo $installer install vlc
    #sudo $installer install docker
    #sudo $installer install sshpass
    sudo $installer install git
    sudo $installer install zip
    sudo $installer install unrar
    #sudo $installer install google-chrome
