# .bashrc
if [ -f ~/.profile ]; then
	. ~/.profile
fi
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
if [ -f ~/.aliases ]; then
	. ~/.aliases
fi

# The next line updates PATH for the Google Cloud SDK.
source '/media/data/workbench/home/jump/Stuffs/gcloud/kits/google-cloud-sdk/path.bash.inc'

# The next line enables shell command completion for gcloud.
source '/media/data/workbench/home/jump/Stuffs/gcloud/kits/google-cloud-sdk/completion.bash.inc'
