#!/bin/bash
export PATH="/usr/local/bin:$PATH"
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
if [ -f ~/.proxy_functions ]; then
  export $(~/.proxy_functions 1)
fi

which kubectl > /dev/null 2>&1
if [ $? -eq 0 ]; then
  source <(kubectl completion zsh)
fi

# GO RELATED
gocode_path="$HOME/data/workspace/gocode"
go_root="$HOME/data/workspace/softs/go"
if [ -d $gocode_path ]; then
  export GOPATH="$gocode_path"
  export PATH="$GOPATH/bin:$PATH"
fi

if [ -d $HOME/gocode ]; then
  export GOPATH="$HOME/gocode"
fi

which go > /dev/null 2>&1
if [ $? -ne 0 ]; then
  export GOROOT="$go_root"
  export PATH="$GOROOT/bin:$PATH"
fi

kube_prompt() {
  kubectl_current_context=$(kubectl config current-context) 2> /dev/null
  if [ $? -ne 0 ]; then 
    return
  fi
  kubectl_project=$(echo $kubectl_current_context | cut -d '_' -f 2)
  #kubectl_cluster=$(echo $kubectl_current_context | cut -d '_' -f 4)
  #kubectl_prompt="k8s:($kubectl_project|$kubectl_cluster)"
  kubectl_prompt="k8s:($kubectl_project)"
  echo "[$kubectl_prompt]"
}

PROMPT='%F{5}[%F{2}%n%F{5}] %F{3}%3~ %{$fg_bold[blue]%}$(kube_prompt)$reset_color ${vcs_info_msg_0_}$reset_color $NEWLINE%#> '
