#!/bin/bash

############## system #############
export EDITOR="/usr/bin/vim"
# lang en_US.ISO-8859-15
export LANG=en_US.ISO-8859-15
export LC_ALL=en_US.ISO-8859-15
export LANGUAGE=en_US.ISO-8859-15
# lang en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
# cvs root
export CVSROOT=:pserver:ciobanan@cvs.intra.vsa.de:/work/cvsdata

############## dev #############
## sybase config ##
source /opt/sqlanywhere11/bin64/sa_config.sh  > /dev/null

## ld library path ##
export LD_LIBRARY_PATH=/opt/sqlanywhere11/lib32/:/opt/sqlanywhere11/lib64:/opt/sqlanywhere11/sun/jre160_x64/lib/amd64/client:/opt/sqlanywhere11/sun/jre160_x64/lib/amd64/server:/opt/sqlanywhere11/sun/jre160_x64/lib/amd64:/opt/sqlanywhere11/sun/jre160_x64/lib/amd64/native_threads
#export LD_LIBRARY_PATH=/opt/sqlanywhere11/lib64:/opt/sqlanywhere11/sun/jre160_x64/lib/amd64/client:/opt/sqlanywhere11/sun/jre160_x64/lib/amd64/server:/opt/sqlanywhere11/sun/jre160_x64/lib/amd64:/opt/sqlanywhere11/sun/jre160_x64/lib/amd64/native_threads:

## paths ##
export M2_HOME="/home/jump/Development/softs/apache-maven-3.3.9"
export M2="$M2_HOME/bin"
export JAVA_HOME="/home/jump/Development/softs/java/jdk1.8.0_25"
#export JAVA_HOME="/home/jump/Development/softs/java/jdk1.8.0_77"
#export JAVA_HOME=/home/jump/Development/softs/sdk
export PATH=/sbin:/opt/sqlanywhere11/bin32:/opt/sqlanywhere11/bin64:$JAVA_HOME/bin:$M2:$PATH

## properties - maven ##
export MAVEN_OPTS="-Xms256m -Xmx512m"
## properties - jump ##
export JBOSS_MEM_OPTS="-XX:MaxPermSize=256m -Xms128m -Xmx968m "
export JUMP_ENV_SERVER="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8787 -DASP_MODE=false -DSynchWorkflowBean.serialize=true"
